// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAVDRXkJLGpoqoQG1AGmqTJQM3EKGu924',
    appId: '1:1055248567801:web:3d4d65641891578bd20128',
    messagingSenderId: '1055248567801',
    projectId: 'codora-app1',
    authDomain: 'codora-app1.firebaseapp.com',
    storageBucket: 'codora-app1.firebasestorage.app',
    measurementId: 'G-LL6BM6F4JP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-_5Y1y1O3mQV2HmzIhsj7mjKjvZMSbr8',
    appId: '1:1055248567801:android:e27474049d164abcd20128',
    messagingSenderId: '1055248567801',
    projectId: 'codora-app1',
    storageBucket: 'codora-app1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHQwe1ROitG219A1FF2zMEz9wgHlZkz_o',
    appId: '1:1055248567801:ios:ca242a618b8c2d27d20128',
    messagingSenderId: '1055248567801',
    projectId: 'codora-app1',
    storageBucket: 'codora-app1.firebasestorage.app',
    iosBundleId: 'com.homy.codora',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHQwe1ROitG219A1FF2zMEz9wgHlZkz_o',
    appId: '1:1055248567801:ios:ca242a618b8c2d27d20128',
    messagingSenderId: '1055248567801',
    projectId: 'codora-app1',
    storageBucket: 'codora-app1.firebasestorage.app',
    iosBundleId: 'com.homy.codora',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAVDRXkJLGpoqoQG1AGmqTJQM3EKGu924',
    appId: '1:1055248567801:web:c280059e8eb958b1d20128',
    messagingSenderId: '1055248567801',
    projectId: 'codora-app1',
    authDomain: 'codora-app1.firebaseapp.com',
    storageBucket: 'codora-app1.firebasestorage.app',
    measurementId: 'G-XBLTD88ZL9',
  );
}