# ุชูููู ูููู ุงูุชุทุจููุงุช ุงูุฃุฑุจุนุฉ ูู ูุดุฑูุน ููุฏูุฑุง
# ูุฐุง ุงูููู ููุถุญ ุงูุชูุธูู ูุงูููุงุนุฏ ููุฐูุงุก ุงูุงุตุทูุงุนู

project_structure:
  name: "ููุฏูุฑุง - Codora"
  type: "Multi-App E-commerce Platform"
  architecture: "4 Separate Applications + Shared Components"

# ุงูุชุทุจููุงุช ุงูุฃุฑุจุนุฉ
applications:
  
  # ุชุทุจูู ุงูุจุงุฆุน - Seller App
  seller:
    name: "ุชุทุจูู ุงูุจุงุฆุน"
    folder: "lib/ุงูููุฏ ุงูุฎุงุต ุจุชุทุจูู ุงูุจุงุฆุน/"
    description: "ุชุทุจูู ุฅุฏุงุฑุฉ ุงููุชุงุฌุฑ ูุงูููุชุฌุงุช ููุจุงุฆุนูู"
    features:
      - "ุฅุฏุงุฑุฉ ุงููุชุฌุฑ"
      - "ุฅุถุงูุฉ/ุชุนุฏูู ุงูููุชุฌุงุช"
      - "ุฅุฏุงุฑุฉ ุงูุทูุจุงุช"
      - "ุงูุชูุงุฑูุฑ ูุงูุฅุญุตุงุฆูุงุช"
      - "ุฅุฏุงุฑุฉ ุงูููุชุฌุงุช ุงูุฃุตููุฉ"
    colors: "๐ช ุฃุฎุถุฑ/ุจุฑุชูุงูู"
    state_management: "GetX"
    widgets: "StatelessWidget only"
    
  # ุชุทุจูู ุงูุชูุตูู - Delivery App  
  delivery:
    name: "ุชุทุจูู ุงูุชูุตูู"
    folder: "lib/ุงูููุฏ ุงูุฎุงุต ุจุชุทุจูู ุงูุชูุตูู/"
    description: "ุชุทุจูู ุฅุฏุงุฑุฉ ุงูุชูุตูู ูุชุชุจุน ุงูุทูุจุงุช"
    features:
      - "ุงุณุชูุงู ุทูุจุงุช ุงูุชูุตูู"
      - "ุชุชุจุน ุงููุณุงุฑุงุช"
      - "ุชุฃููุฏ ุงูุชุณููู"
      - "ุฅุฏุงุฑุฉ ุงูููู ุงูุดุฎุตู"
    colors: "๐ ุฃุฒุฑู/ุฃุตูุฑ"
    state_management: "GetX"
    widgets: "StatelessWidget only"
    
  # ุชุทุจูู ุงูุนููู - Customer App
  customer:
    name: "ุชุทุจูู ุงูุนููู"
    folder: "lib/ุงูููุฏ ุงูุฎุงุต ุจุชุทุจูู ุงูุนููู/"
    description: "ุชุทุจูู ุงูุชุณูู ูุงูุดุฑุงุก ููุนููุงุก"
    features:
      - "ุชุตูุญ ุงูููุชุฌุงุช"
      - "ุงูุจุญุซ ูุงูููุชุฑุฉ"
      - "ุณูุฉ ุงูุชุณูู"
      - "ุฅุชูุงู ุงูุทูุจุงุช"
      - "ุชุชุจุน ุงูุทูุจุงุช"
    colors: "๐ค ุฃุฒุฑู/ุฃุจูุถ"
    state_management: "GetX"
    widgets: "StatelessWidget only"
    
  # ุชุทุจูู ุงูุฃุฏูู - Admin App
  admin:
    name: "ุชุทุจูู ุงูุฃุฏูู"
    folder: "lib/ุงูููุฏ ุงูุฎุงุต ุจุชุทุจูู ุตุงุญุจ ุงูุชุทุจูู/"
    description: "ุชุทุจูู ุฅุฏุงุฑุฉ ุงููุธุงู ูุงูุชุญูู ุงููุงูู"
    features:
      - "ุฅุฏุงุฑุฉ ุงููุณุชุฎุฏููู"
      - "ุฅุฏุงุฑุฉ ุงููุฆุงุช"
      - "ูุฑุงูุจุฉ ุงููุธุงู"
      - "ุงูุชูุงุฑูุฑ ุงูุดุงููุฉ"
      - "ุฅุนุฏุงุฏุงุช ุงูุชุทุจูู"
    colors: "๐จโ๐ผ ุฃุญูุฑ/ุฑูุงุฏู"
    state_management: "GetX"
    widgets: "StatelessWidget only"

# ุงููุฌูุฏ ุงููุดุชุฑู
shared_components:
  name: "ุงูููููุงุช ุงููุดุชุฑูุฉ"
  folder: "lib/shared/"
  description: "ููุฏ ูุดุชุฑู ุจูู ุฌููุน ุงูุชุทุจููุงุช"
  includes:
    - "Services (ุฎุฏูุงุช Firebase ูAPI)"
    - "Utils (ุฃุฏูุงุช ูุณุงุนุฏุฉ)"
    - "Widgets (ุนูุงุตุฑ ูุงุฌูุฉ ูุดุชุฑูุฉ)"
    - "Controllers (ููุชุฑููุฑุงุช ุนุงูุฉ)"
    - "Constants (ุซูุงุจุช ูุดุชุฑูุฉ)"

# ูุฌูุฏ ุงูููุงุฐุฌ ุงููุฑูุฒู
models_folder:
  name: "ููุงุฐุฌ ุงูุจูุงูุงุช"
  folder: "lib/Model/"
  description: "ุฌููุน ููุงุฐุฌ ุงูุจูุงูุงุช (Models) ููุชุทุจููุงุช ุงูุฃุฑุจุนุฉ"
  importance: "ูุฑูุฒู ููุดุชุฑู ุจูู ุฌููุน ุงูุชุทุจููุงุช"
  includes:
    - "ItemModel (ูููุฐุฌ ุงูููุชุฌ)"
    - "UserModel (ูููุฐุฌ ุงููุณุชุฎุฏู)"
    - "OrderModel (ูููุฐุฌ ุงูุทูุจ)"
    - "CategoryModel (ูููุฐุฌ ุงููุฆุฉ)"
    - "CompanyModel (ูููุฐุฌ ุงูุดุฑูุฉ)"
    - "OfferModel (ูููุฐุฌ ุงูุนุฑุถ)"
  required_methods:
    - "fromMap() - ุชุญููู ูู Map ุฅูู Object"
    - "toMap() - ุชุญููู ูู Object ุฅูู Map"
    - "fromJson() - ุชุญููู ูู JSON (ุงุฎุชูุงุฑู)"
    - "toJson() - ุชุญููู ุฅูู JSON (ุงุฎุชูุงุฑู)"
    - "toString() - ุนุฑุถ ูุญุชูู ุงููุงุฆู (ุงุฎุชูุงุฑู)"

# ููุงุนุฏ ุงูุชุทููุฑ
development_rules:
  
  widget_type:
    rule: "ุงุณุชุฎุฏู StatelessWidget ููุท"
    reason: "ูุชุญุณูู ุงูุฃุฏุงุก ูุงุณุชุฎุฏุงู GetX"
    exception: "ูุง ุชูุฌุฏ ุงุณุชุซูุงุกุงุช"
    
  state_management:
    rule: "ุงุณุชุฎุฏู GetX ุญุตุฑูุงู"
    forbidden: ["setState", "Provider", "Bloc", "ValueNotifier"]
    required: ["GetxController", ".obs", "GetBuilder/Obx"]
    
  imports:
    allowed:
      - "ูู ููุณ ุงูุชุทุจูู"
      - "ูู ูุฌูุฏ shared"
      - "ูู ูุฌูุฏ Model"
      - "ูู packages ุฎุงุฑุฌูุฉ"
    forbidden:
      - "ูู ุชุทุจูู ุฅูู ุชุทุจูู ุขุฎุฑ"
    example_correct: "import '../../shared/widgets/loading_widget.dart';"
    example_wrong: "import '../ุงูููุฏ ุงูุฎุงุต ุจุชุทุจูู ุงูุจุงุฆุน/controllers/seller_controller.dart';"
    
  code_separation:
    rule: "ูุตู ูุงูู ุจูู ุงูุชุทุจููุงุช"
    multi_app_features: "ุชูุฑุงุฑ ุงูููุฏ ูู ูู ุชุทุจูู ุจุฏูุงู ูู ุงููุดุงุฑูุฉ"
    mixed_code: "ูุตู ุงูููุฏ ุงููุฎุชูุท ูุชูุฒูุนู ุนูู ุงูุชุทุจููุงุช ุงูููุงุณุจุฉ"
    independence: "ูู ุชุทุจูู ูุณุชูู ุชูุงูุงู ุนู ุงูุขุฎุฑูู"
    exceptions: "ููุท shared components ูุงูููุงุฐุฌ ูููู ูุดุงุฑูุชูุง"

  error_checking:
    auto_fix: true
    trigger: "ุจุนุฏ ูู ุนูููุฉ ุฅูุดุงุก ุฃู ุชุนุฏูู ููุฏ"
    checks:
      - "syntax errors (ุฃุฎุทุงุก ุงูุชุฑููุจ)"
      - "import errors (ุฃุฎุทุงุก ุงูุงุณุชูุฑุงุฏ)"
      - "type errors (ุฃุฎุทุงุก ุงูููุน)"
      - "analysis errors (ุฃุฎุทุงุก ุงูุชุญููู)"
      - "quality warnings (ุชุญุฐูุฑุงุช ุงูุฌูุฏุฉ)"
    max_retries: 3
    tools:
      - "flutter analyze"
      - "dart fix --apply"
      - "custom error detection"
    goal: "ุตูุฑ ุฃุฎุทุงุก ููุงุฆูุงู"

  firebase_management:
    collections_file: "lib/XXX/XXXFirebase.dart"
    reference_class: "FirebaseCollections"
    naming_convention: "snake_case"
    organization:
      - "collections ุฃุณุงุณูุฉ"
      - "collections ุฎุงุตุฉ ุจุงูุจุงุฆุน"
      - "collections ุฎุงุตุฉ ุจุงูุนููู"
      - "collections ุฎุงุตุฉ ุจุงูุชูุตูู"
      - "collections ุฎุงุตุฉ ุจุงูุฃุฏูู"
    auto_detection: true
    enforce_references: true
    prevent_hardcoded_names: true
    
  file_naming:
    convention: "snake_case"
    examples:
      - "product_card_widget.dart"
      - "order_management_controller.dart"
      - "firebase_service.dart"
      
  folder_structure:
    seller: "lib/ุงูููุฏ ุงูุฎุงุต ุจุชุทุจูู ุงูุจุงุฆุน/[controllers|widgets|screens]/"
    delivery: "lib/ุงูููุฏ ุงูุฎุงุต ุจุชุทุจูู ุงูุชูุตูู/[controllers|widgets|screens]/"
    customer: "lib/ุงูููุฏ ุงูุฎุงุต ุจุชุทุจูู ุงูุนููู/[controllers|widgets|screens|class]/"
    admin: "lib/ุงูููุฏ ุงูุฎุงุต ุจุชุทุจูู ุตุงุญุจ ุงูุชุทุจูู/[controllers|widgets|screens]/"
    shared: "lib/shared/[controllers|widgets|services|utils]/"
    models: "lib/Model/[all_models_here]/"

# ุฃูุซูุฉ ููุงุณุชุฎุฏุงู ุงูุตุญูุญ
correct_examples:
  
  widget_creation:
    description: "ุฅูุดุงุก widget ุฌุฏูุฏ"
    correct: |
      class ProductCardWidget extends StatelessWidget {
        final ProductController controller = Get.find();
        
        @override
        Widget build(BuildContext context) {
          return GetBuilder<ProductController>(
            builder: (ctrl) => Container(...)
          );
        }
      }
    
  controller_creation:
    description: "ุฅูุดุงุก controller ุฌุฏูุฏ"
    correct: |
      class ProductController extends GetxController {
        final RxList<Product> products = <Product>[].obs;
        final RxBool isLoading = false.obs;
        
        void loadProducts() {
          isLoading.value = true;
          // ููุทู ุงูุชุญููู
          isLoading.value = false;
        }
      }
      
  shared_component:
    description: "ูููู ูุดุชุฑู"
    correct: |
      // ูู lib/shared/widgets/loading_widget.dart
      class LoadingWidget extends StatelessWidget {
        @override
        Widget build(BuildContext context) {
          return Center(child: CircularProgressIndicator());
        }
      }

# ุฃูุซูุฉ ููุงุณุชุฎุฏุงู ุงูุฎุงุทุฆ
incorrect_examples:
  
  cross_app_import:
    wrong: "import '../seller/controllers/seller_controller.dart'; // ูู customer app"
    correct: "ุงููู ุงูููุฏ ุฅูู shared ุฃู ุงุณุชุฎุฏู interface ูุดุชุฑู"
    
  stateful_widget:
    wrong: "class MyWidget extends StatefulWidget"
    correct: "class MyWidget extends StatelessWidget + GetX Controller"
    
  wrong_state_management:
    wrong: "setState(() => counter++)"
    correct: "counter.value++ // ูุน RxInt counter = 0.obs" 